### ISSUE TITLE
It just a question from new user

### ISSUE THREAD

**Issue by humanisoft** [dhrebeniuk/GaugeMeterView#2]
Hi, I try to use them but I got no succes, someone have a working sample?

Thank in advance

**Comment by dhrebeniuk** [comment]
[TestGauge.zip](https://github.com/dhrebeniuk/GaugeMeterView/files/6353963/TestGauge.zip)

Hello @humanisoft , no problem. Please look example in attachment

**Comment by humanisoft** [comment]
Thank a lot, it appreciate

**Comment by dhrebeniuk** [comment]
@humanisoft , please provide link of application after release :)

**Comment by humanisoft** [comment]
Yes I will provide a link to the app

That normal the needle don't move?

**Comment by dhrebeniuk** [comment]
@humanisoft , no it's should working via: self.gaugeMeterView.value = 30.0 //

I'm used this component in my app: https://apps.apple.com/app/decibel-meter-sound-meter/id1205186197

**Comment by humanisoft** [comment]
Yes your right, it work well, it my fault :-)
Your app look great

**Comment by aalokhyperlink** [comment]
> @humanisoft , no it's should working via: self.gaugeMeterView.value = 30.0 //
> 
> I'm used this component in my app: https://apps.apple.com/app/decibel-meter-sound-meter/id1205186197

How can we change arrow value to high or medium ?
